# config
cover: /img/img-bg.jpg
logo: /img/logo.svg
bio: 东方财富android team blog

# Content
excerpt_link: Read More

# Header  nav
menu:
  Home: /
  Archive: /archive
  Contact: /about/2014-09-11-mabao/

##Private: /private

# nav.fonticon.css
navclass:
  Home: icon-home
  Archive: icon-news
  Images: icon-image
  Wiki: icon-wiki
  Favorites: icon-Favorites
  Contact: icon-mail

##Private: icon-lock
rss: /atom.xml

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
